# Generated by Django 3.2.9 on 2021-12-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Analista',
                'verbose_name_plural': 'Analistas',
                'db_table': 'analistas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_oficio', models.CharField(max_length=25, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('n_pads', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oficio',
                'verbose_name_plural': 'Oficios',
                'db_table': 'oficios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('inicio_ciclo', models.DateField(blank=True, null=True, verbose_name='Inicio del ciclo')),
                ('fin_ciclo', models.DateField(blank=True, null=True, verbose_name='Fin del ciclo')),
                ('n_docentes', models.IntegerField(blank=True, null=True)),
                ('id_analista', models.ForeignKey(blank=True, db_column='id_analista', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.analistas')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'db_table': 'dependencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id_oficio', models.OneToOneField(db_column='id_oficio', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='gestion.oficios')),
                ('altas', models.IntegerField(blank=True, null=True)),
                ('bajas', models.IntegerField(blank=True, null=True)),
                ('sustituciones', models.IntegerField(blank=True, null=True)),
                ('pendientes', models.IntegerField(blank=True, null=True)),
                ('clave_depe', models.ForeignKey(db_column='clave_depe', on_delete=django.db.models.deletion.PROTECT, to='gestion.dependencias')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'db_table': 'envios',
                'managed': True,
                'unique_together': {('id_oficio', 'clave_depe')},
            },
        ),
    ]
