# Generated by Django 3.2.9 on 2021-12-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_oficios_alcance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficios',
            name='alcance',
        ),
        migrations.AddField(
            model_name='oficios',
            name='alcance',
            field=models.ManyToManyField(blank=True, db_column='alcance', default='---', related_name='_gestion_oficios_alcance_+', to='gestion.Oficios'),
        ),
    ]
