# Generated by Django 3.2.9 on 2022-01-21 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_oficios_clave_depe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficios',
            name='clave_depe',
            field=models.ForeignKey(blank=True, db_column='clave_depe', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.dependencias'),
        ),
    ]
